import React from "react";
import { DiCode } from "react-icons/di";
import { FaGithub, FaUniversity, FaVoteYea, FaYCombinator } from "react-icons/fa";
import { SiCocacola, SiWalmart } from "react-icons/si";
import { Education, Experience, Project, TinyTool, Movie } from "./types";
import { BsLinkedin } from "react-icons/bs";
import { EnvelopeClosedIcon } from "@radix-ui/react-icons";
import { FaXTwitter } from "react-icons/fa6";

export const socialLinks = [
  { Icon: FaGithub, href: "https://github.com/DineshTeja" },
  { Icon: BsLinkedin, href: "https://www.linkedin.com/in/dinesh-vasireddy/" },
  { Icon: FaXTwitter, href: "https://twitter.com/dineshtva" },
  { Icon: EnvelopeClosedIcon, href: "mailto:dineshvasireddy@college.harvard.edu" },
];

export const educationData: Education[] = [
  {
    company: "Harvard",
    location: "Cambridge, MA",
    description: "CS & Gov",
    icon: React.createElement(FaUniversity),
    date: "2023",
    src: "/harvard.png",
    href: "https://www.linkedin.com/in/dinesh-vasireddy/",
  },
  {
    company: "Z Fel lows",
    location: "San Francisco, CA",
    description: "https://www.zfellows.com/",
    icon: React.createElement(FaYCombinator),
    date: "2024",
    src: "/z_fellows.jpeg",
    href: "https://www.zfellows.com/",
  },
]

export const tinyTools: TinyTool[] = [
  {
    name: "stack.wrld",
    description: "a beautiful tool to track all of your tech stacks with notion-like notetaking functionality.",
    href: "https://github.com/DineshTeja/stackwrld",
    demo: "https://stackwrld.com/",
    live: false,
  },
  {
    name: "subs.wrld",
    description: "one page tool for tracking your subscriptions.",
    href: "https://github.com/DineshTeja/subscriptions",
    demo: "https://subs.wrld.sh/",
    live: true,
  },
  {
    name: "groq70.wrld",
    description: "simple personal chat interface, using groq models.",
    href: "https://github.com/DineshTeja/groqinterface",
    demo: "https://groq70.wrld.sh/",
    live: false,
  },
  {
    name: "varsa.wrld",
    description: "open-source multilingual LLM playground",
    href: "https://github.com/DineshTeja/varsa",
    demo: "https://varsa.wrld.sh/",
    live: true,
  },
]

export const experiencesData: Experience[] = [
  {
    title: "Engineering, API & Agents",
    company: "Cartesia",
    location: "San Francisco, CA",
    description: "Productizing real-time multimodal intelligence. Launched https://www.cartesia.ai/ink-whisper.",
    icon: React.createElement(FaYCombinator),
    date: "2025",
    src: "/cartesia.png",
    href: "https://www.cartesia.ai/",
    tags: ["Go", "Next.js", "Livekit", "Python"],
  },
  {
    title: "Engineering, AI",
    company: "CoFrame",
    location: "San Francisco, CA",
    description: "Building living interfaces for the web. Automating performance marketing for enterprise (JPM, CapitalOne, NerdWallet).",
    icon: React.createElement(FaYCombinator),
    date: "2025",
    src: "/coframe.png",
    href: "https://www.coframe.com/",
    tags: ["Next.js", "Python","LangGraph", "MongoDB", "LLMs"],
  },
  {
    title: "Engineering",
    company: "GovDash (YC W22)",
    location: "New York, NY",
    description: "AI for GovCon.",
    icon: React.createElement(FaYCombinator),
    date: "2024-25",
    src: "/govdash.png",
    href: "https://govdash.com/",
    tags: ["Next.js", "Python", "LLMs", "Prisma", "Redis", "AWS", "PostgreSQL", "TRPC"],
  },
  {
    title: "Engineering",
    company: "Coca-Cola",
    location: "Cambridge, MA",
    description: "Led a case team to build a black box for market risk and success simulation in the Asia Pacific Operating Unit powered by neural networks, and deployed in production to drive business decisions for 200+ finance analysts.",
    icon: React.createElement(SiCocacola),
    date: "2024",
    src: "/cocacolalogo.png",
    href: "/",
    tags: ["Python", "PyTorch", "Keras", "Google Cloud", "Streamlit"],
  },
  {
    title: "Data Science",
    company: "SkyGrid",
    location: "Cambridge, MA",
    description: "Confidential.",
    icon: React.createElement(DiCode),
    date: "2023",
    src: "/skygrid.png",
    href: "/",
    tags: ["Python", "R", "Statistics"],
  },
  {
    title: "Engineering",
    company: "ClimateNeutral",
    location: "Cambridge, MA",
    description: "Piloted a Custom LLM assistant (Used by 347 Brands) focused on generating comprehensive sustainability plans by analyzing business and sales data. Fine-tuned on international climate standards using transfer learning and domain adaptation.",
    icon: React.createElement(DiCode),
    date: "2023",
    src: "/climateneutral.png",
    href: "/",
    tags: ["Python", "Flask", "LangChain & LangGraph", "Fast.ai", "OpenAI"],
  },
  {
    title: "Founder & CEO",
    company: "PolyData",
    location: "United States of America",
    description:
      "Developed and distributed a collection of contract-bound AI-driven election analysis models focused on optimizing political campaign operations, interpreting electoral outcomes, and understanding voter behavior in local, state, and federal elections. Bootstrapped and scaled to $70K ARR.",
    icon: React.createElement(FaVoteYea),
    date: "2021-23",
    src: "/polydatasmaller_web.png",
    href: "https://polydataelect.vercel.app/",
    tags: ["React", "Python", "TensorFlow", "Supabase", "Google Cloud", "AWS", "D3.js"],
  },
  {
    title: "Engineering, AI & Retail Hardware",
    company: "Walmart Labs",
    location: "Bentonville, AR",
    description:
      "Developed and automated building moving projectors that display signs on retail floors in supercenters nationwide. Created a global E-Commerce Demand Forecasting Model for 6.5M+ Products of Walmart.com sales to optimize online Apparel sales.",
    icon: React.createElement(SiWalmart),
    date: "2021-22",
    src: "/walmartglobal.png",
    href: "https://www.linkedin.com/in/dinesh-vasireddy/",
    tags: ["Python", "PyTorch", "Keras", "AWS", "Element"],
  },
] as const;

export const projectData: Project[] = [
  {
    name: "Bulletproof", 
    tagline: "LLM reasoning enhancement via RL and token simulation",
    description: "Developed Bulletproof, a lightweight reinforcement learning (RL) framework that enhances the reasoning abilities of open-source LLMs by simulating structured reasoning tokens—such as <think>, <verify>, and <conclude>—using Proximal Policy Optimization (PPO). Our approach rewards models for logical consistency, stepwise correctness, and factual accuracy, while penalizing hallucinations and unsupported claims, among other factors, all without requiring large-scale human-annotated datasets.",
    href: "https://github.com/DineshTeja/bulletproof",
    tags: ["HuggingFace", "Llama", "Transformers", "PPO"],
    src: "/bulletproof.png",
    date: "2025",
    links: []
  },
  {
    name: "Supernova", 
    tagline: "AI influencer ad-maker for TikTok",
    description: "Co-developed Supernova, an AI-powered platform that creates TikTok-style ads from just a product link, winning 2nd Place at Stanford Tree Hacks. The system generates realistic short-form content for major brands in under 3 minutes by combining HeyGen and SyncLabs for video generation, Runway for B-roll, Cartesia for voiceovers, and custom market research pipelines powered by Perplexity, Groq, and Deepseek.",
    href: "https://supernova0.vercel.app/",
    tags: ["OpenAI", "Next.js", "HeyGen", "SyncLabs", "Runway", "Cartesia", "Perplexity", "Groq"],
    src: "/supernova.png",
    date: "2025",
    links: [
      {
        name: "Try it out!",
        href: "https://supernova0.vercel.app/",
      },
      
    ]
  },
  {
    name: "SpiceX", 
    tagline: "Explanation framework for LLMs centered around bias-probing",
    description: "Co-developed SPICE-X, a framework that identifies and explains biases in large language models by combining global and contrastive explanation techniques. It analyzes how model outputs shift across demographic attributes, providing actionable insights for bias detection and mitigation in critical domains like healthcare and finance.",
    href: "https://spicexbias.vercel.app/",
    tags: ["Python", "OpenAI", "Next.js", "PyTorch"],
    src: "/spicex.png",
    date: "2024",
  },
  {
    name: "Lightspeed",
    tagline: "AI platform that helps political organizations create winning ads faster",
    description:
    "I'm currently bootstrapping and building Lightspeed, a single AI workflow for political media monitoring, PR, & advertising teams. Lightspeed allows political organizations to make smarter political ads faster and cheaper through real-time insights, social listening, AI ad creation, targeted messaging, and more.",
    href: "https://lightspeedads.netlify.app/",
    tags: ["Next.js", "Python", "OpenAI", "Perplexity", "Supabase"],
    src: "/lightspeed.png",
    date: "2024",
    links: [
      {
        name: "Check it out!",
        href: "https://lightspeedads.netlify.app/",
      },
    ]
  },
  {
    name: "Rally AI",
    tagline: "AI personas for political video ads",
    description:
    "Co-built Rally AI, an AI platform that generates personalized political ads featuring candidate personas. Rally scrapes local news and economic data using Firecrawl and Perplexity, then stores curated insights in a Supabase database. GPT4o-mini crafts speeches in the politician's style, while Cartesia.ai's Sonic text-to-speech creates voice narration. Pexels provides B-roll footage, and SyncLabs lip-syncs the narration to existing footage of the candidate. The final ad integrates stock footage and voice to match relevant voter concerns. Rally AI won 2nd Place Overall and Best Design at PennApps 2024.",
    href: "https://rally-ai.vercel.app/",
    tags: ["Next.js", "Firecrawl", "OpenAI", "Perplexity", "Cartesia.ai", "SyncLabs", "Llama"],
    src: "/rally.png",
    date: "2024",
    links: [
      {
        name: "Try it out!",
        href: "https://rally-ai.vercel.app/",
      },
    ]
  },
  {
    name: "Aria",
    tagline: "conversational video AI for healthcare intelligence",
    description: "Co-built Aria, the first realtime (and human-like) video conversational AI for healthcare intelligence. Aria helps patients ask healthcare questions, receive medical recommendations backed by PubMed and MedlineHealth, and find physician from a network of 100,000+ doctors. Early design partner for Anam.ai, a state-of-the-art AI conversational video API.",
    href: "https://ariamed.vercel.app/",
    tags: ["Next.js", "Python", "OpenAI", "Groq", "Llama", "Supabase", "Anam.ai"],
    src: "/aria.png",
    date: "2024",
    links: [
      {
        name: "Try it out!",
        href: "https://ariamed.vercel.app/",
      },
      {
        name: "Github",
        href: "https://github.com/DineshTeja/aria",
      }, 
      {
        name: "Devpost",
        href: "https://devpost.com/software/aria-sc10g2",
      }
    ]
  },
  {
    name: "Commonwealth.ai",
    tagline: "Political research and structured data engine",
    description:
    "Built a political research engine that indexes articles, enables semantic search, and extracts structured data using LLMs and RAG. 2150+ users (a few paid), 12000+ articles indexed, and 15 campaign users on our first product.",
    href: "https://commonwealthai.netlify.app/",
    tags: ["React", "Next.js", "Supabase", "OpenAI", "Deno", "LLMs"],
    src: "/commonwealthlogo.png",
    date: "2024",
  },
  {
    name: "AccesSOS",
    tagline: "Translation tool for globalizing web products",
    description:
      "Led a team of software engineers to build a translation database tool for AccesSOS' devs to easily convert their websites into multiple languages. The tool is built with React, Next.js, and Supabase.",
    href: "/",
    tags: ["React", "Next.js", "Supabase", "Google Cloud", "Python"],
    src: "/accessos.png",
    date: "2024",
  },
  {
    name: "Resilience Week 2023",
    tagline: "LLMs, Cybersecurity, & Defense (IEEE published)",
    description:
      "Conducted and led NSF-sponsored research advised by Prof. Qinghua Li at UARK's Cybersecurity Center for Secure Evolvable Energy Delivery Systems (SEEDS) investigating the use of language learning models and machine learning algorithms (Doc2Vec, Fast.ai, Advanced BERT Models) to improve the Common Vulnerability Scoring System and effectively classify computer system vulnerabilities. Accepted for publication by Defense TechConnect for Resilience Week 2023 in Washington D.C.",
    href: "https://ieeexplore.ieee.org/document/10284627",
    tags: ["Python", "Flask", "Google Cloud", "Fast.ai", "LLMs", "BERT"],
    src: "/rweek.png",
    date: "2023",
    links: [
      {
        name: "Publication",
        href: "https://ieeexplore.ieee.org/document/10284627",
      },
    ]
  },
  {
    name: "Arkansas United",
    tagline: "Automated resources portal for Arkansas United",
    description: "Developed and launched an online automated resources portal AUNow (2K+ National Users, 10+ Partners, 50K Visits, Largest in Arkansas). Created machine learning models for electoral analysis and social media listening to develop optimized technology-related policy proposals.",
    href: "https://www.arkansasunited.org/",
    tags: ["Next.js", "Python", "Firebase", "Render"],
    src: "/arkansasunited.png",
    date: "2023",
  },
  {
    name: "Datategy",
    tagline: "ML algorithms for financial analysis",
    description:
      "Developed, optimized, and deployed three new machine learning algorithms, focused on financial analysis and data management, for Datategy's PapAI Business AI Platform (20+ International Clients).",
    href: "https://www.datategy.net/",
    tags: ["Python", "PyTorch", "TensorFlow", "Keras", "AWS"],
    src: "/datategy.png",
    date: "2022",
  },
] as const;

export const projectsData = [
  {
    title: "Commonwealth.ai",
    description:
      "Built a political research engine that indexes and performs sentiment analysis on political articles to create an efficient standard and verifiable structure for news articles, enables semantic search via LLMs and RAG, facilitates instant LLM-powered structured list creation, bulk data extraction on a granular level, and supports research thread management. We're creating a high-speed pipeline for extracting structured data from the treasure trove that is news media.",
    tags: ["React", "Next.js", "Supabase", "OpenAI", "Deno", "LLMs"],
    imageUrl: "/commonwealthlogo.png",
    url: "https://commonwealthai.netlify.app/",
  },
  {
    title: "AnyCheck",
    description:
      "Assembled an application utilizing a custom-trained large language model enhanced via relevant news articles, integrated speech recognition, and real-time analytical feedback, designed to enhance information accuracy through voice-activated claims submission and comprehensive PDF essay analysis.",
    tags: ["Flask", "Google Cloud", "Fast.ai", "BERT", "LLMs"],
    imageUrl: "/anychecklogo.png",
    url: "https://www.linkedin.com/in/dinesh-vasireddy/",
  },
  {
    title: "ClimateNeutral LLM",
    description:
      "Piloted a Custom LLM assistant (Used by 347 Brands) focused on generating comprehensive sustainability plans by analyzing business and sales data. Fine-tuned on international climate standards using transfer learning and domain adaptation.",
    tags: ["Flask", "Langchain", "Fast.ai", "LLMs"],
    imageUrl: "/climateneutral.png",
    url: "https://www.linkedin.com/in/dinesh-vasireddy/",
  },
  {
    title: "PolyData Electoral Innovation",
    description:
      "Developed and distributed a collection of contract-bound AI-driven election analysis models focused on optimizing political campaign operations, interpreting electoral outcomes, and understanding voter behavior in local, state, and federal elections.",
    tags: ["React", "Python", "TensorFlow", "Google Cloud", "AWS", "D3.js"],
    imageUrl: "/polydatasmaller_web.png",
    url: "https://www.linkedin.com/in/dinesh-vasireddy/",
  },
] as const;

export const favoriteMovies: Movie[] = [
  // English
  {
    title: "The Shawshank Redemption",
    year: 1994,
    director: "Frank Darabont",
    genre: "Drama",
    posterUrl: "/posters/shawshank.png",
    rating: 9.5,
    language: "English",
  },
  {
    title: "Rocky",
    year: 1976,
    director: "John G. Avildsen",
    genre: "Sports Drama",
    posterUrl: "/posters/rocky.png",
    rating: 9.0,
    language: "English",
  },
  {
    title: "Logan",
    year: 2017,
    director: "James Mangold",
    genre: "Superhero Drama",
    posterUrl: "/posters/logan.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Ex Machina",
    year: 2014,
    director: "Alex Garland",
    genre: "Science Fiction",
    posterUrl: "/posters/ex-machina.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "The Pursuit of Happyness",
    year: 2006,
    director: "Gabriele Muccino",
    genre: "Biographical Drama",
    posterUrl: "/posters/pursuit.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Iron Man",
    year: 2008,
    director: "Jon Favreau",
    genre: "Superhero Science Fiction",
    posterUrl: "/posters/iron-man.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    genre: "Epic Science Fiction",
    posterUrl: "/posters/interstellar.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "No Country for Old Men",
    year: 2007,
    director: "Joel & Ethan Coen",
    genre: "Neo-Western Crime Thriller",
    posterUrl: "/posters/no-country-for-old-men.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "The Social Network",
    year: 2010,
    director: "David Fincher",
    genre: "Biographical Drama",
    posterUrl: "/posters/social-network.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "The Passion of the Christ",
    year: 2004,
    director: "Mel Gibson",
    genre: "Religious Drama",
    posterUrl: "/posters/passion-of-the-christ.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "The Godfather",
    year: 1972,
    director: "Francis Ford Coppola",
    genre: "Epic Gangster Drama",
    posterUrl: "/posters/the-godfather.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Good Will Hunting",
    year: 1997,
    director: "Gus Van Sant",
    genre: "Drama",
    posterUrl: "/posters/good-will-hunting.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Star Wars: The Empire Strikes Back",
    year: 1980,
    director: "Irvin Kershner",
    genre: "Epic Space Opera",
    posterUrl: "/posters/star-wars-empire.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Malcolm X",
    year: 1992,
    director: "Spike Lee",
    genre: "Biographical Drama",
    posterUrl: "/posters/malcolm-x.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Get Out",
    year: 2017,
    director: "Jordan Peele",
    genre: "Psychological Horror",
    posterUrl: "/posters/get-out.png",
    rating: 8.5,
    language: "English",
  },
  { 
    title: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    genre: "Psychological Horror",
    posterUrl: "/posters/silence-of-the-lambs.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "The Dark Knight",
    year: 2008,
    director: "Christopher Nolan",
    genre: "Action Thriller",
    posterUrl: "/posters/the-dark-knight.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "The Martian",
    year: 2015,
    director: "Ridley Scott",
    genre: "Space & Science Fiction",
    posterUrl: "/posters/the-martian.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "Black Panther",
    year: 2018,
    director: "Ryan Coogler",
    genre: "Superhero Action",
    posterUrl: "/posters/black-panther.png",
    rating: 8.5,
    language: "English",
  },
  {
    title: "21 Jump Street",
    year: 2012,
    director: "Phil Lord & Christopher Miller",
    genre: "Action Comedy",
    posterUrl: "/posters/21-jump-street.png",
    rating: 8.5,
    language: "English",
  },
  // Telugu
  {
    title: "Baahubali: The Beginning",
    year: 2015,
    director: "S. S. Rajamouli",
    genre: "Epic Action",
    posterUrl: "/posters/baahubali.png",
    rating: 9.0,
    language: "Telugu",
  },
  {
    title: "Rangasthalam",
    year: 2018,
    director: "Sukumar",
    genre: "Action Thriller",
    posterUrl: "/posters/rangasthalam.png",
    rating: 8.7,
    language: "Telugu",
  },
  {
    title: "Vedam",
    year: 2010,
    director: "Krish Jagarlamudi",
    genre: "Melodrama Anthology",
    posterUrl: "/posters/vedam.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Aravinda Sametha Veera Raghava",
    year: 2018,
    director: "Trivikram Srinivas",
    genre: "Action Drama",
    posterUrl: "/posters/aravinda-sametha.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Jersey",
    year: 2019,
    director: "Gowtam Tinnanuri",
    genre: "Sports Drama",
    posterUrl: "/posters/jersey.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Prasthanam",
    year: 2010,
    director: "Deva Katta",
    genre: "Political Action Drama",
    posterUrl: "/posters/prasthanam.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Shiva",
    year: 1989,
    director: "Ram Gopal Varma",
    genre: "Crime Action",
    posterUrl: "/posters/shiva.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Temper",
    year: 2015,
    director: "Puri Jagannadh",
    genre: "Action Drama",
    posterUrl: "/posters/temper.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Seethamma Vakitlo Sirimalle Chettu",
    year: 2013,
    director: "Srikanth Addala",
    genre: "Family Drama",
    posterUrl: "/posters/svsc.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Pokiri",
    year: 2006,
    director: "Puri Jagannadh",
    genre: "Action Thriller",
    posterUrl: "/posters/pokiri.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Kick",
    year: 2009,
    director: "Surender Reddy",
    genre: "Action Comedy",
    posterUrl: "/posters/kick.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Vikramarkudu",
    year: 2006,
    director: "S. S. Rajamouli",
    genre: "Action Drama",
    posterUrl: "/posters/vikramarkudu.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Goodachari",
    year: 2018,
    director: "Sashi Kiran Tikka",
    genre: "Spy Thriller",
    posterUrl: "/posters/goodachari.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Brochevarevarura",
    year: 2019,
    director: "Vivek Athreya",
    genre: "Crime Comedy",
    posterUrl: "/posters/brochevarevarura.png",
    rating: 8.5,
    language: "Telugu",
  },
  {
    title: "Nuvvostanante Nenoddantana",
    year: 2005,
    director: "Prabhu Deva",
    genre: "Romantic Comedy",
    posterUrl: "/posters/nuvvostanante-nenoddantana.png",
    rating: 8.5,
    language: "Telugu",
  },
  // Tamil
  {
    title: "Anbe Sivam",
    year: 2003,
    director: "Sundar C.",
    genre: "Slice-of-life Drama",
    posterUrl: "/posters/anbe-sivam.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Vikram Vedha",
    year: 2017,
    director: "Pushkar & Gayatri",
    genre: "Neo-Noir Action",
    posterUrl: "/posters/vikram-vedha.png",
    rating: 9.0,
    language: "Tamil",
  },
  {
    title: "Jigarthanda Double X",
    year: 2023,
    director: "Karthik Subbaraj",
    genre: "Period Action Drama",
    posterUrl: "/posters/jigarthanda-doublex.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Soorarai Pottru",
    year: 2020,
    director: "Sudha Kongara",
    genre: "Drama",
    posterUrl: "/posters/soorarai-pottru.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Nayakan",
    year: 1987,
    director: "Mani Ratnam",
    genre: "Epic Crime Drama",
    posterUrl: "/posters/nayakan.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "96",
    year: 2018,
    director: "C. Prem Kumar",
    genre: "Romantic Drama",
    posterUrl: "/posters/96.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Kaithi",
    year: 2019,
    director: "Lokesh Kanagaraj",
    genre: "Action Thriller",
    posterUrl: "/posters/kaithi.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Ratsasan",
    year: 2018,
    director: "Ram Kumar",
    genre: "Action Thriller",
    posterUrl: "/posters/ratsasan.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Aadukalam",
    year: 2011,
    director: "Vetrimaran",
    genre: "Drama",
    posterUrl: "/posters/aadukalam.png",
    rating: 8.5,
    language: "Tamil",
  },
  {
    title: "Bison Kaalamaadan",
    year: 2025,
    director: "Mari Selvaraj",
    genre: "Sports Action Drama",
    posterUrl: "/posters/bison.png",
    rating: 8.5,
    language: "Tamil",
  },
  // Kannada
  {
    title: "KGF: Chapter 2",
    year: 2022,
    director: "Prashanth Neel",
    genre: "Action Drama",
    posterUrl: "/posters/kgf2.png",
    rating: 9.0,
    language: "Kannada",
  },
  {
    title: "Kantara",
    year: 2022,
    director: "Rishab Shetty",
    genre: "Action Thriller",
    posterUrl: "/posters/kantara.png",
    rating: 9.0,
    language: "Kannada",
  },
] as const;